### ISSUE TITLE
CORS Error

### ISSUE THREAD

**Issue by killy10o10** [SpecialistSteak/peoplegenerator-api#1]
I get this error when I try to use your API in my app. 

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://peoplegeneratorapi.live/api/person/100. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.

is there a way I can go around this?

**Comment by ltmerletti** [comment]
Hey, sorry about the late reply! I've been pretty busy these past few months. 

Basically, this is happening due to how it's configured on my end, I believe it only allows for you to use the API on websites if they're on the same server as mine, currently.

I'll quickly fix that issue (through enabling CORS), and reboot the server so you (or whoever wants to) can use it by tomorrow, hopefully.

Cheers!

**Comment by ltmerletti** [comment]
I'm going to mark this issue as resolved now, everything should work now!
